"""empty message

Revision ID: 993336a25e8a
Revises: 2f5290ac5242
Create Date: 2020-05-02 03:02:34.768995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993336a25e8a'
down_revision = '2f5290ac5242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
